<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer:
### Hidden Layer:
### Output Layer:
### Neuron:
### Weight:
### Activation Function:
### Node Map:
### Perceptron:


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### Your Answer Here

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [25]:
import pandas as pd
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0],
         'b': [1,1,1,1]
       }

df = pd.DataFrame.from_dict(data).astype('int')

In [26]:
##### Your Code Here #####
df.shape


(4, 4)

In [27]:
inputs = df

In [28]:
outputs = ([1],[1],[1],[0])

In [29]:
import numpy as np

In [30]:
weights = 2 * np.random.random((4,1)) - 1

In [33]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1 - sx)

In [34]:
weighted_sum = np.dot(inputs, weights)

In [35]:
# first output
activated_output = sigmoid(weighted_sum)
activated_output

array([[0.19259822],
       [0.17011089],
       [0.18050757],
       [0.31982917]])

In [36]:
# Find the error
error = data['y'] - activated_output
error

array([[ 0.80740178,  0.80740178,  0.80740178, -0.19259822],
       [ 0.82988911,  0.82988911,  0.82988911, -0.17011089],
       [ 0.81949243,  0.81949243,  0.81949243, -0.18050757],
       [ 0.68017083,  0.68017083,  0.68017083, -0.31982917]])

In [37]:
# Gradient descent, finding the steepest slope to lower error

adjustments = error * sigmoid_derivative(weighted_sum)
adjustments.shape

(4, 4)

In [38]:
# Forward Propagation time

for i in range(10000):
  # dot product the inputs and weights to get weighted sum
  weighted_sum = np.dot(inputs, weights)
  
  # activation function, could add bias here if you wanted
  activated_output = sigmoid(weighted_sum)

  # actual - predicted = error
  error = outputs - activated_output

  # Back Prop time
  adjustments = error * sigmoid_derivative(weighted_sum)

  # Update wthe weights with the dot product of inputs.T and adjustments
  weights = weights + np.dot(inputs.T, adjustments)
print("Weights after training")
print(weights)

print("Output after training")
print(activated_output)

Weights after training
[[-2.93043345]
 [-2.93011019]
 [ 6.97614722]
 [ 1.05625185]]
Output after training
[[0.99967531]
 [0.99395172]
 [0.99395366]
 [0.00812831]]


## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [39]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [40]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

features = list(diabetes)[:-1]
target = list(diabetes)[-1:]

#instantiate normalizer. This is used because different features have different ranges.

normalizer = Normalizer()

#normalize feature data

X = normalizer.fit_transform(diabetes[features])

#target
y = diabetes[target]



In [41]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.25, random_state=42)

In [49]:
##### Update this Class #####

class Perceptron:
    
    def __init__(self, niter = 10):
        self.niter = niter
    
    def __sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def __sigmoid_derivative(self, x):
        sx = sigmoid(x)
        return sx * (1-sx)

    def fit(self, X, y):  
       # Randomly Initialize Weights
        self.weight = 2 * np.random.random((8,1)) - 1 #8 here is the number of input vectors. Outcome column is our target / prediction variable

        for i in range(self.niter):
            # Weighted sum of inputs / weights
            weighted_sum = np.dot(X, self.weight) #input vectors multiplied by randomly assigned weights.
            # Activate!
            activated_output = self.__sigmoid(weighted_sum) #weighted sum is passed through an activation function, here it is a sigmoid function.
            # Cac error
            error = y - activated_output #checking for error by difference between activated output and the target y 
            adjustments = error * self.__sigmoid_derivative(weighted_sum) #adjustment value that is used to redefine weights in the next step
            # Update the Weights
            self.weight = self.weight + np.dot(X.T, adjustments) #adding the adjustments to existing randomized weight values to make it closer to target y.


    def predict(self, X):
        """Return class label after unit step"""
        weighted_sum = np.dot(X, self.weight) + 1
        activated_output = self.__sigmoid(weighted_sum)
        return np.round(activated_output)

In [50]:
model = Perceptron()
model.fit(X,y)
model.predict(X)

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?